spring:
  datasource:
    url: jdbc:mysql:///shop_1901
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    #配置数据库链接池为阿里的druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 60000
  rabbitmq:
    host: 192.168.141.129
    username: guest
    password: guest
    port: 5672
    virtual-host: /
dubbo:
  application:
    name: service_goods
  registry:
    address: zookeeper://192.168.141.129:2181
  protocool:
    name: dubbo
    port: -1