spring:
  data:
    solr:
      host: http://192.168.141.129:8080/solr
  rabbitmq:
    host: 192.168.141.129
    username: guest
    password: guest
    port: 5672
    virtual-host: /
dubbo:
  application:
    name: service_search
  registry:
    address: zookeeper://192.168.141.129:2181
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 60000
